list_data = {
    'bcpp_subject.circumcisionbenefits': [
        ('Improved hygiene ', 'Improved hygiene '),
        ('Reduced risk of HIV ', 'Reduced risk of HIV '),
        ('Reduced risk of other sexually transmitted diseases', 'Reduced risk of other sexually transmitted diseases'),
        ('Reduced risk of cancer', 'Reduced risk of cancer'),
        ('Other', 'Other'),
        ('I am not sure', 'I am not sure'),
        ("Don't want to answer", "Don't want to answer")],
    'bcpp_subject.diagnoses': [
        ('Heart Disease or Stroke', 'Heart Disease'),
        ('Cancer', 'Cancer'),
        ('Tubercolosis', 'tb'),
        ('Other serious infection', 'Other'),
        ('None', 'none'),
        ('STI (Sexually Transmitted Infection)', 'sti')],
    'bcpp_subject.ethnicgroups': [
        ('Babirwa', 'Babirwa'),
        ('Bahambukushu', 'Bahambukushu'),
        ('Baherero', 'Baherero'),
        ('Bahurutshe', 'Bahurutshe'),
        ('Bakalaka', 'Bakalaka'),
        ('Bakgatla', 'Bakgatla'),
        ('Bakwena', 'Bakwena'),
        ('Balete', 'Balete'),
        ('Bangwaketse', 'Bangwaketse'),
        ('Bangwato', 'Bangwato'),
        ('Bakgalagadi', 'Bakgalagadi'),
        ('Basarwa', 'Basarwa'),
        ('Basobea', 'Basobea'),
        ('Batawana', 'Batawana'),
        ('Batlokwa', 'Batlokwa'),
        ('Batswapong', 'Batswapong'),
        ('White African', 'White African'),
        ('Indian African', 'Indian African'),
        ('Asian', 'Asian'),
        ('Other, specify', 'Other, specify'),
        ("Don't want to answer", 'dont want to answer'),
        ('Bazezuri/Shona', 'Bazezuri')],
    'bcpp_subject.familyplanning': [
        ('Condoms, consistent use (male or female)', 'Condoms, consistent use (male or female)'),
        ('Injectable contraceptive', 'Injectable contraceptive'),
        ('Oral contraceptive', 'Oral contraceptive'),
        ('IUD', 'IUD'),
        ('Diaphragm or cervical cap', 'Diaphragm or cervical cap'),
        ('Rhythm or menstrual cycle timing', 'Rhythm or menstrual cycle timing'),
        ('Withdrawal', 'Withdrawal'),
        ('Other, specify', 'Other, specify'),
        ("Don't want to answer", "Don't want to answer"),
        ('NOT APPLICABLE', 'NA'),
        ('Condoms, in-consistent use (male or female)', 'Condoms, in-consistent use (male or female)')],
    'bcpp_subject.heartdisease': [
        ('Myocardial infarction (heart attack)', 'Myocardial infarction (heart attack)'),
        ('Congestive cardiac failure', 'Congestive cardiac failure'),
        ('Stroke (cerebrovascular accident, CVA)', 'Stroke (cerebrovascular accident, CVA)'),
        ('Other, specify', 'Other, specify'),
        ("Don't want to answer", "Don't want to answer")],
    'bcpp_subject.livewith': [
        ('Partner or spouse', 'Partner or spouse'),
        ('Siblings', 'Siblings'),
        ('Alone', 'Alone'),
        ('Extended family', 'Extended family'),
        ('Other', 'Other'),
        ("Don't want to answer", "Don't want to answer")],
    'bcpp_subject.medicalcareaccess': [
        ('Traditional, faith, or religious healer/doctor', 'Traditional, faith, or religious healer/doctor'),
        ('Pharmacy', 'Pharmacy'),
        ('Public or government health facility or clinic', 'Public or government health facility or clinic'),
        ('Private health facility or clinic', 'Private health facility or clinic'),
        ('Community health worker', 'Community health worker'),
        ('Other, specify', 'Other, specify'),
        ("Don't want to answer", 'dont want to answer')],
    'bcpp_subject.neighbourhoodproblems': [
        ('Water', 'Water'),
        ('Sewer (sanitation)', 'Sewer (sanitation)'),
        ('Housing', 'Housing'),
        ('Roads', 'Roads'),
        ('Malaria', 'Malaria'),
        ('HIV/AIDS', 'HIV/AIDS'),
        ('Schools', 'Schools'),
        ('Unemployment', 'Unemployment'),
        ('Other, specify', 'Other, specify'),
        ("Don't want to answer", "Don't want to answer")],
    'bcpp_subject.partnerresidency': [
        ('In this community', 'in this community'),
        ('Outside community', 'outside community'),
        ('Farm within this community', 'farm within'),
        ('Farm outside this community', 'farm outside this community'),
        ('Cattle post within this community', 'cattelepost within'),
        ('Cattle post outside this community', 'cattlepost outside')],
    'bcpp_subject.religion': [
        ('Anglican', 'anglican'),
        ('Apostolic', 'apostolic'),
        ('Baptist', 'baptist'),
        ('Catholic', 'catholic'),
        ('Evangelical', 'evangelical'),
        ('Methodist', 'methodist'),
        ('Pentecostal', 'pentecostal'),
        ('Traditionalist', 'traditionalist'),
        ('ZCC', 'zcc'),
        ('Islam', 'muslim'),
        ('HInduism', 'hindu'),
        ('Buddhism', 'buddhist'),
        ('Other, specify', 'Other, specify'),
        ('No affiliation', 'no_affiliation')],
    'bcpp_subject.stiillnesses': [
        ('Severe weight loss (wasting) - more than 10% of body weight', 'wasting'),
        ('Unexplained diarrhoea for one month', 'diarrhoea'),
        ('Yeast infection of mouth or oesophagus', 'yeast_infection'),
        ('Severe pneumonia or meningitis or sepsis', 'pneumonia'),
        ('PCP (Pneumocystis pneumonia)', 'PCP'),
        ('Herpes infection for more than one month', 'herpes'),
        ('Other, specify', 'Other, specify'),
        ('None', 'None')],
}
