from .circumcision_benefits import CircumcisionBenefits
from .diagnoses import Diagnoses
from .electrical_appliances import ElectricalAppliances
from .ethnic_groups import EthnicGroups
from .family_planning import FamilyPlanning
from .heart_disease import HeartDisease
from .live_with import LiveWith
from .medical_care_access import MedicalCareAccess
from .neighbourhood_problems import NeighbourhoodProblems
from .partner_residency import PartnerResidency
from .religion import Religion
from .resident_most_likely import ResidentMostLikely
from .sti_illnesses import StiIllnesses
from .transport_mode import TransportMode
